# Generated by Django 5.1.6 on 2025-03-02 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cnel. Oviedo',
        ),
        migrations.DeleteModel(
            name='IAE',
        ),
        migrations.DeleteModel(
            name='ICM',
        ),
        migrations.DeleteModel(
            name='IEK',
        ),
        migrations.DeleteModel(
            name='IEL',
        ),
        migrations.DeleteModel(
            name='IEN',
        ),
        migrations.DeleteModel(
            name='IIN',
        ),
        migrations.DeleteModel(
            name='IMK',
        ),
        migrations.DeleteModel(
            name='ISP',
        ),
        migrations.DeleteModel(
            name='LCA',
        ),
        migrations.DeleteModel(
            name='LCI',
        ),
        migrations.DeleteModel(
            name='LCIk',
        ),
        migrations.DeleteModel(
            name='LEL',
        ),
        migrations.DeleteModel(
            name='LGH',
        ),
        migrations.DeleteModel(
            name='TSE',
        ),
    ]
