# Generated by Django 5.1.6 on 2025-03-02 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cnel_oviedo_icm_iek_ien_iin_imk_isp_lca_lci_lcik_lel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cnel_Oviedo',
        ),
        migrations.DeleteModel(
            name='IAE',
        ),
        migrations.DeleteModel(
            name='ICM',
        ),
        migrations.DeleteModel(
            name='IEK',
        ),
        migrations.DeleteModel(
            name='IEN',
        ),
        migrations.DeleteModel(
            name='IIN',
        ),
        migrations.DeleteModel(
            name='IMK',
        ),
        migrations.DeleteModel(
            name='ISP',
        ),
        migrations.DeleteModel(
            name='LCA',
        ),
        migrations.DeleteModel(
            name='LCI',
        ),
        migrations.DeleteModel(
            name='LCIk',
        ),
        migrations.DeleteModel(
            name='LEL',
        ),
        migrations.DeleteModel(
            name='LGH',
        ),
        migrations.DeleteModel(
            name='TSE',
        ),
    ]
