# Generated by Django 5.1.6 on 2025-03-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_carrera_materia_delete_cnel_oviedo_delete_iae_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materia',
            old_name='horario',
            new_name='horario_semanal',
        ),
        migrations.RenameField(
            model_name='materia',
            old_name='creditos',
            new_name='nivel',
        ),
        migrations.AddField(
            model_name='materia',
            name='primer_final',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materia',
            name='primer_parcial',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materia',
            name='seccion',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materia',
            name='segundo_final',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materia',
            name='segundo_parcial',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
