# Generated by Django 5.1.6 on 2025-03-02 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('creditos', models.IntegerField()),
                ('profesor', models.CharField(max_length=100)),
                ('horario', models.CharField(max_length=100)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='app.carrera')),
            ],
        ),
        migrations.DeleteModel(
            name='Cnel. Oviedo',
        ),
        migrations.DeleteModel(
            name='IAE',
        ),
        migrations.DeleteModel(
            name='ICM',
        ),
        migrations.DeleteModel(
            name='IEK',
        ),
        migrations.DeleteModel(
            name='IEL',
        ),
        migrations.DeleteModel(
            name='IEN',
        ),
        migrations.DeleteModel(
            name='IIN',
        ),
        migrations.DeleteModel(
            name='IMK',
        ),
        migrations.DeleteModel(
            name='ISP',
        ),
        migrations.DeleteModel(
            name='LCA',
        ),
        migrations.DeleteModel(
            name='LCI',
        ),
        migrations.DeleteModel(
            name='LCIk',
        ),
        migrations.DeleteModel(
            name='LEL',
        ),
        migrations.DeleteModel(
            name='LGH',
        ),
        migrations.DeleteModel(
            name='TSE',
        ),
    ]
