# Generated by Django 5.1.6 on 2025-03-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_horario_materia_horario_semanal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='horario_semanal',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='materia',
            name='primer_final',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materia',
            name='primer_parcial',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materia',
            name='segundo_final',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materia',
            name='segundo_parcial',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
